config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicle_types do
    member do
      get 'duplicate_existing'
    end
  end

  resources :projects

  get 'welcome/index'
  get 'load_builder/:project_id/add_vehicle', to: 'load_builder#add_vehicle'
  get 'load_builder/add_item', to: 'load_builder#add_item'
  get 'load_builder/:project_id', to: 'load_builder#index'
  get 'load_builder/:project_id/save_position',  to: 'load_builder#save_position'
  get 'load_builder/:project_id/delete_element', to: 'load_builder#delete_element'
  get 'load_builder/:project_id/rotate', to: 'load_builder#rotate'

  get 'projects/:id/manifest', to: 'projects#manifest'

  root 'welcome#index'

  resources :items
  resources :vehicles

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_vehicles, dependent: :destroy
  has_many :vehicles, through: :project_vehicles
  has_many :project_items, dependent: :destroy
  has_many :items, through: :project_items

  accepts_nested_attributes_for :project_items,
                                {:reject_if => lambda { |a| a[:item_id].blank? }, 
                                :allow_destroy => true }

  accepts_nested_attributes_for :project_vehicles,
                                { :reject_if => lambda { |a| a[:vehicle_id].blank? },
                                :allow_destroy => true }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :manifest]
  layout 'application', :except => [:manifest]
	  
  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
    @project.project_items.build 
    @project.project_vehicles.build 
  end

  def edit
    @project.project_items.build
    @project.project_vehicles.build 
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to edit_project_path(@project), notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Basic freight manifest report of the projects load
  def manifest
    render :manifest
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
        :id, :title, :owner, :project_items, :project_vehicles,
        project_items_attributes: [:id, :note, :item_id, :_destroy],
        project_vehicles_attributes: [:id, :vehicle_id, :_destroy]
      )
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div>
    <%= f.label :project_items %><br>
    <%= f.fields_for :project_items do |builder| %>
  	  <%= render 'project_item_fields', :f => builder %>
    <% end %>
  </div>
  <div>
    <%= f.label :project_vehicles %><br>
    <%= f.fields_for :project_vehicles do |builder| %>
  	  <%= render 'project_vehicle_fields', :f => builder %>
    <% end %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_manifest_table.erb
<table class="manifest">
	<thead>
		<tr>
			<th>#</th>
			<th>Item</th>
			<th>KGS</th>
			<th>M3</th>
		</tr>
	</thead>
	<tbody>
                <% total_kgs = 0 %>
                <% total_m3  = 0 %>
		<% @project.project_items.each_with_index do |pi, i| %>
		<tr>
			<td><%= i+1 %></td>
			<td><%= truncate(pi.item.desc) %></td>
			<td><%= pi.item.kgs %></td>
			<td><%= pi.item.m3.round(3) %></td>
                        <% total_kgs += pi.item.kgs %>
                        <% total_m3  += pi.item.m3 %>
		</tr>
		<% end %>
		<tr>
                  <td colspan="2"><b>Total Required</b></td>
                        <td><b><%= total_kgs %></b></td>
                        <td><b><%= total_m3.round(3) %></b></td>
		</tr>
                <% total_vehicle_m3  = 0 %>
		<% @project.project_vehicles.each_with_index do |pi, i| %>
		<tr>
			<td><%= i+1 %></td>
			<td><%= truncate(pi.vehicle.desc) %></td>
			<td></td>
			<td><%= pi.vehicle.m3.round(3) %></td>
                        <% total_vehicle_m3  += pi.vehicle.m3 %>
		</tr>
		<% end %>
		<tr>
                  <td colspan="2"><b>Max Capacity</b></td>
			<td></td>
                        <td><b><%= total_vehicle_m3.round(3) %></b></td>
		</tr>
	</tbody>
</table>

app/views/projects/_project_item_fields.html.erb
<div class="fields">
  <%= f.label :item %>
  <%= f.collection_select :item_id, Item.all, :id, :desc, include_blank: true %>    
  <%= f.label :note %>
  <%= f.text_field :note %>
  <%= f.label :x %>
  <%= f.text_field :x %>
  <%= f.label :y %>
  <%= f.text_field :y %>
  <%= f.check_box :_destroy, class: 'destroy_input' %>
  (remove)
</div>

app/views/projects/_project_vehicle_fields.html.erb
<div class="fields">
  <%= f.label :vehicle %>
  <%= f.collection_select :vehicle_id, Vehicle.all, :id, :desc, include_blank: true %>    
  <%= f.check_box :_destroy, class: 'destroy_input' %>
  (remove)
</div>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<div>
<p class="text-success bg-success"><%= notice %></p>
</div>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Manifest', :controller => :projects, :action => :manifest %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<div class="top-buttons">
  <%= link_to 'New Project', new_project_path, :class => 'btn btn-default btn-sm'  %>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Owner</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.owner %></td>
	<td><%= link_to 'Build Load', {controller: 'load_builder', action: 'index', project_id: project.id}, class: 'btn btn-primary btn-xs'%></td>
	<td><%= link_to 'Show', project, :class => 'btn btn-default btn-xs' %></td>
	<td><%= link_to 'Edit', edit_project_path(project), :class => 'btn btn-default btn-xs'%></td>
	<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-xs' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/projects/manifest.erb
<h1>Project Manifest</h1>
<%= render 'manifest_table' %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div>
<p class="text-success bg-success"><%= notice %></p>
</div>

<h1>Project: <%= @project.title %></h1>

<p>
  <strong>Owner:</strong>
  <%= @project.owner %>
</p>

<h2>Items in Project</h2>
<ol>
<% @project.project_items.each do |project_item| %>
    <li><%= project_item.item.desc if project_item.item != nil %> - <%= project_item.note %></li>
<% end %>
</ol>

<h2>Vehicles in Project</h2>
<% @project.vehicles.each do |v| %>
    <p><%= v.desc %></p>
<% end %>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>