config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicle_types do
    member do
      get 'duplicate_existing'
    end
  end

  resources :projects

  get 'welcome/index'
  get 'load_builder/:project_id/add_vehicle', to: 'load_builder#add_vehicle'
  get 'load_builder/add_item', to: 'load_builder#add_item'
  get 'load_builder/:project_id', to: 'load_builder#index'
  get 'load_builder/:project_id/save_position',  to: 'load_builder#save_position'
  get 'load_builder/:project_id/delete_element', to: 'load_builder#delete_element'
  get 'load_builder/:project_id/rotate', to: 'load_builder#rotate'

  get 'projects/:id/manifest', to: 'projects#manifest'

  root 'welcome#index'

  resources :items
  resources :vehicles

end

app/models/item.rb
# Item of freight common definition
class Item < ActiveRecord::Base
  #has_one :project, through: :project_items
  validates :desc, presence: true,
                   length: { minimum: 3 }

  def m3
    l * w * h
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
 
    if @item.save
      redirect_to @item
    else
      render 'new'
    end
    
  end
  
  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
 
    if @item.update(item_params)
      redirect_to @item
    else
      render 'edit'
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy
 
    redirect_to items_path
  end

  private
  
    def item_params
      params.require(:item).permit(:desc, :l, :w, :h)
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Editing Item</h1>
 
<%= form_for :item, url: item_path(@item), method: :patch do |f| %>
  <% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited
      this item from being saved:</h2>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </p>
 
  <p>
    <%= f.label :l %><br>
    <%= f.text_field :l %>
  </p>

  <p>
    <%= f.label :w %><br>
    <%= f.text_field :w %>
  </p>

  <p>
    <%= f.label :h %><br>
    <%= f.text_field :h %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>
 
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Items</h1>

<div class="top-buttons">
<%= link_to 'New Item', new_item_path, :class => 'btn btn-default btn-sm' %>
</div>

<table class="table table-condensed">
  <tr>
    <th>Description</th>
    <th>Dims</th>
    <th colspan="3"></th>
  </tr>
 
  <% @items.each do |item| %>
    <tr>
      <td><%= item.desc %></td>
      <td><%= item.l %> x <%= item.w %> x <%= item.h %></td>
      <td><%= link_to 'Show', item_path(item), :class => 'btn btn-default btn-xs' %></td>
      <td><%= link_to 'Edit', edit_item_path(item), :class => 'btn btn-default btn-xs' %></td>
      <td><%= link_to 'Destroy', item_path(item),
                    method: :delete,
                    :class => 'btn btn-default btn-xs' %>
      </td>
    </tr>
  <% end %>
 
</table>

app/views/items/new.html.erb
<h1>New Item (Piece, Pallet, Container, etc.)</h1>
<%= form_for :item, url: items_path do |f| %>

  <% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited
      this item from being saved:</h2>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </p>
 
  <p>
    <%= f.label :l %><br>
    <%= f.text_field :l %>
  </p>

  <p>
    <%= f.label :w %><br>
    <%= f.text_field :w %>
  </p>

  <p>
    <%= f.label :h %><br>
    <%= f.text_field :h %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Desc:</strong>
  <%= @item.desc %>
</p>
 
<p>
  <strong>Dims:</strong>
  <%= @item.l %> x <%= @item.w %> x <%= @item.h %>
</p>

<%= link_to 'Back', items_path %>