config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicle_types do
    member do
      get 'duplicate_existing'
    end
  end

  resources :projects

  get 'welcome/index'
  get 'load_builder/:project_id/add_vehicle', to: 'load_builder#add_vehicle'
  get 'load_builder/add_item', to: 'load_builder#add_item'
  get 'load_builder/:project_id', to: 'load_builder#index'
  get 'load_builder/:project_id/save_position',  to: 'load_builder#save_position'
  get 'load_builder/:project_id/delete_element', to: 'load_builder#delete_element'
  get 'load_builder/:project_id/rotate', to: 'load_builder#rotate'

  get 'projects/:id/manifest', to: 'projects#manifest'

  root 'welcome#index'

  resources :items
  resources :vehicles

end

app/models/vehicle.rb
# Vehicle (or loadable container) that can accept items of freight
# l,w,h are the dimensions of the loadable area of the vehicle
# x,y are coordinates with origin (0,0) top left of a north facing vehicle

class Vehicle < ActiveRecord::Base
  has_many :project_vehicles
  has_many :projects, through: :project_vehicles
  has_many :vehicle_items
  has_many :items, through: :vehicle_items
  
  def m3
	l * w * h
  end
  
  # attempt to place an item on this vehicle at x,y
  def place(item, x, y)
    if in_bounds(x, y) && fits_in(item, x, y)
      items << item
    end  
  end
  
  def fits_in(item, x, y)  
    x + item.w <= self.w && y + item.l <= self.l
  end
  
  def in_bounds(x, y)
    x >= 0.0 && x < self.w && y >= 0.0 && y < self.l
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  def index
    @vehicles = Vehicle.all
  end

  def show
  end

  def new
    @vehicle = Vehicle.new
  end

  def edit
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def duplicate_existing
    existing = VehicleType.find(params[:id])
    @vehicle_type = existing.dup
    render 'new'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:desc, :size_class, :l, :w, :h, :gvm)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :size_class %><br>
    <%= f.text_field :size_class %>
  </div>
  <div class="field">
    <%= f.label :l %><br>
    <%= f.text_field :l %>
  </div>
  <div class="field">
    <%= f.label :w %><br>
    <%= f.text_field :w %>
  </div>
  <div class="field">
    <%= f.label :h %><br>
    <%= f.text_field :h %>
  </div>
  <div class="field">
    <%= f.label :gvm %><br>
    <%= f.number_field :gvm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<div class="top-buttons">
  <%= link_to 'New Vehicle', new_vehicle_path, :class => 'btn btn-default btn-sm' %>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Desc</th>
      <th>Size/Class</th>
      <th>L</th>
      <th>W</th>
      <th>H</th>
      <th>Gvm</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.desc %></td>
        <td><%= vehicle.size_class %></td>
        <td><%= vehicle.l %></td>
        <td><%= vehicle.w %></td>
        <td><%= vehicle.h %></td>
        <td><%= vehicle.gvm %></td>
        <td><%= link_to 'Show', vehicle, :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle), :class => 'btn btn-default btn-xs' %></td>
        <td><%= link_to 'Destroy', vehicle_path(vehicle),
                          {method: :delete, 
			  data: { confirm: 'Are you sure?' }, 
			  class: 'btn btn-default btn-xs'} %>
		
	</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @vehicle.desc %>
</p>

<p>
  <strong>Size/Class:</strong>
  <%= @vehicle.size_class %>
</p>

<p>
  <strong>L:</strong>
  <%= @vehicle.l %>
</p>

<p>
  <strong>W:</strong>
  <%= @vehicle.w %>
</p>

<p>
  <strong>H:</strong>
  <%= @vehicle.h %>
</p>

<p>
  <strong>Gvm:</strong>
  <%= @vehicle.gvm %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>