config/routes.rb
Rails.application.routes.draw do
  
  resources :vehicle_types do
    member do
      get 'duplicate_existing'
    end
  end

  resources :projects

  get 'welcome/index'
  get 'load_builder/:project_id/add_vehicle', to: 'load_builder#add_vehicle'
  get 'load_builder/add_item', to: 'load_builder#add_item'
  get 'load_builder/:project_id', to: 'load_builder#index'
  get 'load_builder/:project_id/save_position',  to: 'load_builder#save_position'
  get 'load_builder/:project_id/delete_element', to: 'load_builder#delete_element'
  get 'load_builder/:project_id/rotate', to: 'load_builder#rotate'

  get 'projects/:id/manifest', to: 'projects#manifest'

  root 'welcome#index'

  resources :items
  resources :vehicles

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Truck Tool</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <span class="glyphicon glyphicon-home"></span>
          Truck Tool
        <% end %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class=""><%= link_to("Projects", projects_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Maintenance<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Vehicles", items_path %></li>
              <li><%= link_to "Items", items_path %></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">

     <div class="">

     <%= yield %>

     </div>

  </div>

</body>
</html>